---
- hosts: local

  vars:
    dysk: 'sda'
    montowanie: '/mnt/dysk'
    partycja_glowna: '1'
    fs: 'ext4'


  tasks:
  
    - name: Sprawdzanie systemu
      fail: msg="SYSTEM LIVE MUSI BYC 64-bitowy"
      when: ansible_architecture != "x86_64"

    - name: Partycje
      import_tasks: dysk_ubuntu.yml
      when: ansible_distribution == "Ubuntu"
      tags: dysk

    - name: Tworzenie katalogu montowania
      file:
        path: "{{ montowanie }}"
        state: directory
        mode: 0755
      tags: wzorzec

    - name: Montowanie dysku
      mount:
        path: "{{ montowanie }}"
        src: "/dev/{{ dysk }}{{ partycja_glowna }}"
        fstype: "{{ fs }}"
        fstab: /tmp/fstab.tmp
        state: mounted
      tags: wzorzec

    - name: Wzorzec
      import_tasks: wzorzec.yml
      tags: wzorzec
   
    - name: chroot
      command: chroot /mnt/dysk grub-install /dev/sda
      tags: wzorzec
   
#- import_playbook: chroot.yml
#  tags: wzorzec
